vich_uploader:
    db_driver: orm
    mappings:
        cours_pdf:
            uri_prefix: /pdfs
            upload_destination: '%kernel.project_dir%/public/pdfs'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            
           
            

        signalement_images:
            uri_prefix: '%kernel.project_dir%/public/uploads/signalement'
            upload_destination: '%kernel.project_dir%/public/uploads/signalement'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
