# config/services.yaml
parameters:
    images_annonces_directory: '%kernel.project_dir%/public/imagesAnnonces'
    pdf_directory: '%kernel.project_dir%/public/pdfs'
    images_signalements_directory: '%kernel.project_dir%/public/uploads/signalement'
    uploads_directory: '%kernel.project_dir%/public/uploads'
    stripe_secret_key: '%env(STRIPE_SECRET_KEY)%'
    stripe_sk: '%env(STRIPE_SK)%'
    stripe_pk: '%env(STRIPE_PK)%'
    stripe_webhook_secret: '%env(STRIPE_WEBHOOK_SECRET)%'


services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $passwordHasher: '@Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface'

    # Configuration pour les contrôleurs
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # Configuration pour les dépôts (repositories)
    App\Repository\:
        resource: '../src/Repository/'

    # Configuration pour les services de sécurité
    App\Security\:
        resource: '../src/Security/'
        autowire: true

    # Configuration globale pour l'application
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

# Configuration Twig (doit être dans un fichier séparé ou dans le bon contexte)
twig:
    globals:
        current_user: '@security.token_storage'