parameters:
    images_annonces_directory: '%kernel.project_dir%/public/imagesAnnonces'
    pdf_directory: '%kernel.project_dir%/public/pdfs'
    images_signalements_directory: '%kernel.project_dir%/public/uploads/signalement'
    uploads_directory: '%kernel.project_dir%/public/uploads'

twig:
    globals:
        current_user: '@security.token_storage'

services:
    _defaults:
        autowire: true      # Active l'autowiring pour tous les services
        autoconfigure: true # Active l'autoconfiguration pour tous les services
        public: false       # Rend les services privés par défaut

        # Liaisons communes (bindings)
        bind:
            $passwordHasher: '@Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface'

    # Enregistrement des contrôleurs
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # Enregistrement des services de sécurité
    App\Security\:
        resource: '../src/Security/'
        autowire: true

    # Enregistrement de tous les services dans src/
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # Configuration manuelle du service MailerService
    App\Service\MailerService:
        arguments:
            $mailer: '@Symfony\Component\Mailer\MailerInterface'
            $from: 'Ihebcherni60@gmail.com'


    App\Service\NotificationService:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'

            
    App\Service\FeedbackRatingService: ~
